syntax = "proto3";
package proto;
option go_package = "code-analyser/protos/pb/plugin";

import "protos/plugin/common.proto";
import "protos/output/global/makefile.proto";

service MakeFileService {
  rpc Detect(ServiceInputString) returns (ServiceOutputMakeFile);
}

message ServiceOutputMakeFile{
  ServiceError error = 1;
  protos.output.global.MakefileOutput makeFile = 2;
}
