syntax = "proto3";
package proto;
option go_package = "code-analyser/protos/pb/plugin";

import "protos/plugin/common.proto";
import "protos/output/global/makefile.proto";

service MakeFile {
  rpc Detect(StringInput) returns (MakeFileOutput);
}

message MakeFileOutput {
  Error error = 1;
  protos.output.global.MakeFile makefile = 2;
}
