syntax = "proto3";
package protos.output.global;
import "protos/output/global/command.proto";

option go_package = "code-analyser/protos/pb/output/global";
message DockerFileOutput{
  bool used = 1;
  string filePath = 2;
  repeated Command commands = 3;
}