// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: protos/versions/globalPLugin.proto

package versions

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GlobalPlugin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DockerFile string `protobuf:"bytes,1,opt,name=dockerFile,proto3" json:"dockerFile,omitempty"`
	ProcFile   string `protobuf:"bytes,2,opt,name=procFile,proto3" json:"procFile,omitempty"`
	MakeFile   string `protobuf:"bytes,3,opt,name=makeFile,proto3" json:"makeFile,omitempty"`
	Commands   string `protobuf:"bytes,4,opt,name=commands,proto3" json:"commands,omitempty"`
}

func (x *GlobalPlugin) Reset() {
	*x = GlobalPlugin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_versions_globalPLugin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalPlugin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalPlugin) ProtoMessage() {}

func (x *GlobalPlugin) ProtoReflect() protoreflect.Message {
	mi := &file_protos_versions_globalPLugin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalPlugin.ProtoReflect.Descriptor instead.
func (*GlobalPlugin) Descriptor() ([]byte, []int) {
	return file_protos_versions_globalPLugin_proto_rawDescGZIP(), []int{0}
}

func (x *GlobalPlugin) GetDockerFile() string {
	if x != nil {
		return x.DockerFile
	}
	return ""
}

func (x *GlobalPlugin) GetProcFile() string {
	if x != nil {
		return x.ProcFile
	}
	return ""
}

func (x *GlobalPlugin) GetMakeFile() string {
	if x != nil {
		return x.MakeFile
	}
	return ""
}

func (x *GlobalPlugin) GetCommands() string {
	if x != nil {
		return x.Commands
	}
	return ""
}

var File_protos_versions_globalPLugin_proto protoreflect.FileDescriptor

var file_protos_versions_globalPLugin_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x2f, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x50, 0x4c, 0x75, 0x67, 0x69, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x82, 0x01, 0x0a, 0x0c, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c,
	0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72,
	0x46, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x6f, 0x63, 0x6b,
	0x65, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x63, 0x46, 0x69,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x63, 0x46, 0x69,
	0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61, 0x6b, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x61, 0x6b, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x42, 0x22, 0x5a, 0x20, 0x63, 0x6f,
	0x64, 0x65, 0x2d, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2f, 0x70, 0x62, 0x2f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_versions_globalPLugin_proto_rawDescOnce sync.Once
	file_protos_versions_globalPLugin_proto_rawDescData = file_protos_versions_globalPLugin_proto_rawDesc
)

func file_protos_versions_globalPLugin_proto_rawDescGZIP() []byte {
	file_protos_versions_globalPLugin_proto_rawDescOnce.Do(func() {
		file_protos_versions_globalPLugin_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_versions_globalPLugin_proto_rawDescData)
	})
	return file_protos_versions_globalPLugin_proto_rawDescData
}

var file_protos_versions_globalPLugin_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_versions_globalPLugin_proto_goTypes = []interface{}{
	(*GlobalPlugin)(nil), // 0: protos.versions.GlobalPlugin
}
var file_protos_versions_globalPLugin_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_versions_globalPLugin_proto_init() }
func file_protos_versions_globalPLugin_proto_init() {
	if File_protos_versions_globalPLugin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_versions_globalPLugin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlobalPlugin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_versions_globalPLugin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_versions_globalPLugin_proto_goTypes,
		DependencyIndexes: file_protos_versions_globalPLugin_proto_depIdxs,
		MessageInfos:      file_protos_versions_globalPLugin_proto_msgTypes,
	}.Build()
	File_protos_versions_globalPLugin_proto = out.File
	file_protos_versions_globalPLugin_proto_rawDesc = nil
	file_protos_versions_globalPLugin_proto_goTypes = nil
	file_protos_versions_globalPLugin_proto_depIdxs = nil
}
