// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DependenciesServiceClient is the client API for DependenciesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DependenciesServiceClient interface {
	GetDependencies(ctx context.Context, in *ServiceInput, opts ...grpc.CallOption) (*ServiceOutputStringMap, error)
}

type dependenciesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDependenciesServiceClient(cc grpc.ClientConnInterface) DependenciesServiceClient {
	return &dependenciesServiceClient{cc}
}

func (c *dependenciesServiceClient) GetDependencies(ctx context.Context, in *ServiceInput, opts ...grpc.CallOption) (*ServiceOutputStringMap, error) {
	out := new(ServiceOutputStringMap)
	err := c.cc.Invoke(ctx, "/proto.DependenciesService/GetDependencies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DependenciesServiceServer is the server API for DependenciesService service.
// All implementations must embed UnimplementedDependenciesServiceServer
// for forward compatibility
type DependenciesServiceServer interface {
	GetDependencies(context.Context, *ServiceInput) (*ServiceOutputStringMap, error)
	//mustEmbedUnimplementedDependenciesServiceServer()
}

// UnimplementedDependenciesServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDependenciesServiceServer struct {
}

func (UnimplementedDependenciesServiceServer) GetDependencies(context.Context, *ServiceInput) (*ServiceOutputStringMap, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDependencies not implemented")
}
func (UnimplementedDependenciesServiceServer) mustEmbedUnimplementedDependenciesServiceServer() {}

// UnsafeDependenciesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DependenciesServiceServer will
// result in compilation errors.
type UnsafeDependenciesServiceServer interface {
	mustEmbedUnimplementedDependenciesServiceServer()
}

func RegisterDependenciesServiceServer(s grpc.ServiceRegistrar, srv DependenciesServiceServer) {
	s.RegisterService(&DependenciesService_ServiceDesc, srv)
}

func _DependenciesService_GetDependencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DependenciesServiceServer).GetDependencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DependenciesService/GetDependencies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DependenciesServiceServer).GetDependencies(ctx, req.(*ServiceInput))
	}
	return interceptor(ctx, in, info, handler)
}

// DependenciesService_ServiceDesc is the grpc.ServiceDesc for DependenciesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DependenciesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DependenciesService",
	HandlerType: (*DependenciesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDependencies",
			Handler:    _DependenciesService_GetDependencies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dependencies.proto",
}
