// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: proto/library.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceOutputLibraryType_Type int32

const (
	ServiceOutputLibraryType_REPLACED ServiceOutputLibraryType_Type = 0
	ServiceOutputLibraryType_EXTERNAL ServiceOutputLibraryType_Type = 1
)

// Enum value maps for ServiceOutputLibraryType_Type.
var (
	ServiceOutputLibraryType_Type_name = map[int32]string{
		0: "REPLACED",
		1: "EXTERNAL",
	}
	ServiceOutputLibraryType_Type_value = map[string]int32{
		"REPLACED": 0,
		"EXTERNAL": 1,
	}
)

func (x ServiceOutputLibraryType_Type) Enum() *ServiceOutputLibraryType_Type {
	p := new(ServiceOutputLibraryType_Type)
	*p = x
	return p
}

func (x ServiceOutputLibraryType_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceOutputLibraryType_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_library_proto_enumTypes[0].Descriptor()
}

func (ServiceOutputLibraryType_Type) Type() protoreflect.EnumType {
	return &file_proto_library_proto_enumTypes[0]
}

func (x ServiceOutputLibraryType_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceOutputLibraryType_Type.Descriptor instead.
func (ServiceOutputLibraryType_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_library_proto_rawDescGZIP(), []int{0, 0}
}

type ServiceOutputLibraryType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value bool                          `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Type  ServiceOutputLibraryType_Type `protobuf:"varint,3,opt,name=type,proto3,enum=proto.ServiceOutputLibraryType_Type" json:"type,omitempty"`
	Error *ServiceError                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ServiceOutputLibraryType) Reset() {
	*x = ServiceOutputLibraryType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_library_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceOutputLibraryType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceOutputLibraryType) ProtoMessage() {}

func (x *ServiceOutputLibraryType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_library_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceOutputLibraryType.ProtoReflect.Descriptor instead.
func (*ServiceOutputLibraryType) Descriptor() ([]byte, []int) {
	return file_proto_library_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceOutputLibraryType) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

func (x *ServiceOutputLibraryType) GetType() ServiceOutputLibraryType_Type {
	if x != nil {
		return x.Type
	}
	return ServiceOutputLibraryType_REPLACED
}

func (x *ServiceOutputLibraryType) GetError() *ServiceError {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_proto_library_proto protoreflect.FileDescriptor

var file_proto_library_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xb9, 0x01, 0x0a, 0x18, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x38, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x54, 0x79,
	0x70, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x29, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x22, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0c,
	0x0a, 0x08, 0x45, 0x58, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x10, 0x01, 0x32, 0xca, 0x01, 0x0a,
	0x0e, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x3e, 0x0a, 0x06, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x1f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x37, 0x0a, 0x06, 0x49, 0x73, 0x55, 0x73, 0x65, 0x64, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x18,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x3f, 0x0a, 0x0d, 0x50, 0x65, 0x72, 0x63,
	0x65, 0x6e, 0x74, 0x4f, 0x66, 0x55, 0x73, 0x65, 0x64, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x19,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2e, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_library_proto_rawDescOnce sync.Once
	file_proto_library_proto_rawDescData = file_proto_library_proto_rawDesc
)

func file_proto_library_proto_rawDescGZIP() []byte {
	file_proto_library_proto_rawDescOnce.Do(func() {
		file_proto_library_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_library_proto_rawDescData)
	})
	return file_proto_library_proto_rawDescData
}

var file_proto_library_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_library_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_library_proto_goTypes = []interface{}{
	(ServiceOutputLibraryType_Type)(0), // 0: proto.ServiceOutputLibraryType.Type
	(*ServiceOutputLibraryType)(nil),   // 1: proto.ServiceOutputLibraryType
	(*ServiceError)(nil),               // 2: proto.ServiceError
	(*ServiceInput)(nil),               // 3: proto.ServiceInput
	(*ServiceOutputBool)(nil),          // 4: proto.ServiceOutputBool
	(*ServiceOutputFloat)(nil),         // 5: proto.ServiceOutputFloat
}
var file_proto_library_proto_depIdxs = []int32{
	0, // 0: proto.ServiceOutputLibraryType.type:type_name -> proto.ServiceOutputLibraryType.Type
	2, // 1: proto.ServiceOutputLibraryType.error:type_name -> proto.ServiceError
	3, // 2: proto.LibraryService.Detect:input_type -> proto.ServiceInput
	3, // 3: proto.LibraryService.IsUsed:input_type -> proto.ServiceInput
	3, // 4: proto.LibraryService.PercentOfUsed:input_type -> proto.ServiceInput
	1, // 5: proto.LibraryService.Detect:output_type -> proto.ServiceOutputLibraryType
	4, // 6: proto.LibraryService.IsUsed:output_type -> proto.ServiceOutputBool
	5, // 7: proto.LibraryService.PercentOfUsed:output_type -> proto.ServiceOutputFloat
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_library_proto_init() }
func file_proto_library_proto_init() {
	if File_proto_library_proto != nil {
		return
	}
	file_proto_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_library_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceOutputLibraryType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_library_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_library_proto_goTypes,
		DependencyIndexes: file_proto_library_proto_depIdxs,
		EnumInfos:         file_proto_library_proto_enumTypes,
		MessageInfos:      file_proto_library_proto_msgTypes,
	}.Build()
	File_proto_library_proto = out.File
	file_proto_library_proto_rawDesc = nil
	file_proto_library_proto_goTypes = nil
	file_proto_library_proto_depIdxs = nil
}
