# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos.plugin import common_pb2 as protos_dot_plugin_dot_common__pb2


class PreDetectCommandStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunPreDetect = channel.unary_unary(
                '/proto.PreDetectCommand/RunPreDetect',
                request_serializer=protos_dot_plugin_dot_common__pb2.ServiceInput.SerializeToString,
                response_deserializer=protos_dot_plugin_dot_common__pb2.ServiceEmptyOutput.FromString,
                )


class PreDetectCommandServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunPreDetect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PreDetectCommandServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunPreDetect': grpc.unary_unary_rpc_method_handler(
                    servicer.RunPreDetect,
                    request_deserializer=protos_dot_plugin_dot_common__pb2.ServiceInput.FromString,
                    response_serializer=protos_dot_plugin_dot_common__pb2.ServiceEmptyOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.PreDetectCommand', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PreDetectCommand(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunPreDetect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.PreDetectCommand/RunPreDetect',
            protos_dot_plugin_dot_common__pb2.ServiceInput.SerializeToString,
            protos_dot_plugin_dot_common__pb2.ServiceEmptyOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
