// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        (unknown)
// source: detected.proto

package protos

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Detections struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Language  string          `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Percent   int64           `protobuf:"varint,2,opt,name=percent,proto3" json:"percent,omitempty"`
	Framework string          `protobuf:"bytes,3,opt,name=framework,proto3" json:"framework,omitempty"`
	Output    *DetectedOutput `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *Detections) Reset() {
	*x = Detections{}
	if protoimpl.UnsafeEnabled {
		mi := &file_detected_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Detections) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detections) ProtoMessage() {}

func (x *Detections) ProtoReflect() protoreflect.Message {
	mi := &file_detected_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detections.ProtoReflect.Descriptor instead.
func (*Detections) Descriptor() ([]byte, []int) {
	return file_detected_proto_rawDescGZIP(), []int{0}
}

func (x *Detections) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Detections) GetPercent() int64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *Detections) GetFramework() string {
	if x != nil {
		return x.Framework
	}
	return ""
}

func (x *Detections) GetOutput() *DetectedOutput {
	if x != nil {
		return x.Output
	}
	return nil
}

type Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Root     string        `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Detected []*Detections `protobuf:"bytes,2,rep,name=Detected,json=detected,proto3" json:"Detected,omitempty"`
	// list of files docker files
	DockerFiles []string `protobuf:"bytes,3,rep,name=dockerFiles,proto3" json:"dockerFiles,omitempty"`
	// list of files make files
	MakeFiles []string `protobuf:"bytes,4,rep,name=makeFiles,proto3" json:"makeFiles,omitempty"`
	// list of files proc files
	ProcFile []string `protobuf:"bytes,5,rep,name=procFile,proto3" json:"procFile,omitempty"`
}

func (x *Output) Reset() {
	*x = Output{}
	if protoimpl.UnsafeEnabled {
		mi := &file_detected_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_detected_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_detected_proto_rawDescGZIP(), []int{1}
}

func (x *Output) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *Output) GetDetected() []*Detections {
	if x != nil {
		return x.Detected
	}
	return nil
}

func (x *Output) GetDockerFiles() []string {
	if x != nil {
		return x.DockerFiles
	}
	return nil
}

func (x *Output) GetMakeFiles() []string {
	if x != nil {
		return x.MakeFiles
	}
	return nil
}

func (x *Output) GetProcFile() []string {
	if x != nil {
		return x.ProcFile
	}
	return nil
}

var File_detected_proto protoreflect.FileDescriptor

var file_detected_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x0e, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x89, 0x01, 0x0a, 0x0a, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x70, 0x65,
	0x72, 0x63, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f,
	0x72, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x77,
	0x6f, 0x72, 0x6b, 0x12, 0x27, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x65, 0x64, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0xa1, 0x01, 0x0a,
	0x06, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x12, 0x27, 0x0a, 0x08, 0x44,
	0x65, 0x74, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x08, 0x64, 0x65, 0x74, 0x65,
	0x63, 0x74, 0x65, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x46, 0x69,
	0x6c, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x6f, 0x63, 0x6b, 0x65,
	0x72, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x6b, 0x65, 0x46, 0x69,
	0x6c, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x61, 0x6b, 0x65, 0x46,
	0x69, 0x6c, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x63, 0x46, 0x69, 0x6c, 0x65,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x63, 0x46, 0x69, 0x6c, 0x65,
	0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_detected_proto_rawDescOnce sync.Once
	file_detected_proto_rawDescData = file_detected_proto_rawDesc
)

func file_detected_proto_rawDescGZIP() []byte {
	file_detected_proto_rawDescOnce.Do(func() {
		file_detected_proto_rawDescData = protoimpl.X.CompressGZIP(file_detected_proto_rawDescData)
	})
	return file_detected_proto_rawDescData
}

var file_detected_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_detected_proto_goTypes = []interface{}{
	(*Detections)(nil),     // 0: Detections
	(*Output)(nil),         // 1: Output
	(*DetectedOutput)(nil), // 2: DetectedOutput
}
var file_detected_proto_depIdxs = []int32{
	2, // 0: Detections.output:type_name -> DetectedOutput
	0, // 1: Output.Detected:type_name -> Detections
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_detected_proto_init() }
func file_detected_proto_init() {
	if File_detected_proto != nil {
		return
	}
	file_detector_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_detected_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Detections); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_detected_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Output); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_detected_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_detected_proto_goTypes,
		DependencyIndexes: file_detected_proto_depIdxs,
		MessageInfos:      file_detected_proto_msgTypes,
	}.Build()
	File_detected_proto = out.File
	file_detected_proto_rawDesc = nil
	file_detected_proto_goTypes = nil
	file_detected_proto_depIdxs = nil
}
