# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/plugin/library.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.plugin import common_pb2 as protos_dot_plugin_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/plugin/library.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'Z\036code-analyser/protos/pb/plugin',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1bprotos/plugin/library.proto\x12\x05proto\x1a\x1aprotos/plugin/common.proto\"\xa5\x01\n\x18ServiceOutputLibraryType\x12\r\n\x05value\x18\x01 \x01(\x08\x12\x32\n\x04type\x18\x03 \x01(\x0e\x32$.proto.ServiceOutputLibraryType.Type\x12\"\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x13.proto.ServiceError\"\"\n\x04Type\x12\x0c\n\x08REPLACED\x10\x00\x12\x0c\n\x08\x45XTERNAL\x10\x01\x32\xca\x01\n\x0eLibraryService\x12>\n\x06\x44\x65tect\x12\x13.proto.ServiceInput\x1a\x1f.proto.ServiceOutputLibraryType\x12\x37\n\x06IsUsed\x12\x13.proto.ServiceInput\x1a\x18.proto.ServiceOutputBool\x12?\n\rPercentOfUsed\x12\x13.proto.ServiceInput\x1a\x19.proto.ServiceOutputFloatB Z\x1e\x63ode-analyser/protos/pb/pluginb\x06proto3'
  ,
  dependencies=[protos_dot_plugin_dot_common__pb2.DESCRIPTOR,])



_SERVICEOUTPUTLIBRARYTYPE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='proto.ServiceOutputLibraryType.Type',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REPLACED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EXTERNAL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=198,
  serialized_end=232,
)
_sym_db.RegisterEnumDescriptor(_SERVICEOUTPUTLIBRARYTYPE_TYPE)


_SERVICEOUTPUTLIBRARYTYPE = _descriptor.Descriptor(
  name='ServiceOutputLibraryType',
  full_name='proto.ServiceOutputLibraryType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.ServiceOutputLibraryType.value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='proto.ServiceOutputLibraryType.type', index=1,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='proto.ServiceOutputLibraryType.error', index=2,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SERVICEOUTPUTLIBRARYTYPE_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=232,
)

_SERVICEOUTPUTLIBRARYTYPE.fields_by_name['type'].enum_type = _SERVICEOUTPUTLIBRARYTYPE_TYPE
_SERVICEOUTPUTLIBRARYTYPE.fields_by_name['error'].message_type = protos_dot_plugin_dot_common__pb2._SERVICEERROR
_SERVICEOUTPUTLIBRARYTYPE_TYPE.containing_type = _SERVICEOUTPUTLIBRARYTYPE
DESCRIPTOR.message_types_by_name['ServiceOutputLibraryType'] = _SERVICEOUTPUTLIBRARYTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServiceOutputLibraryType = _reflection.GeneratedProtocolMessageType('ServiceOutputLibraryType', (_message.Message,), {
  'DESCRIPTOR' : _SERVICEOUTPUTLIBRARYTYPE,
  '__module__' : 'protos.plugin.library_pb2'
  # @@protoc_insertion_point(class_scope:proto.ServiceOutputLibraryType)
  })
_sym_db.RegisterMessage(ServiceOutputLibraryType)


DESCRIPTOR._options = None

_LIBRARYSERVICE = _descriptor.ServiceDescriptor(
  name='LibraryService',
  full_name='proto.LibraryService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=235,
  serialized_end=437,
  methods=[
  _descriptor.MethodDescriptor(
    name='Detect',
    full_name='proto.LibraryService.Detect',
    index=0,
    containing_service=None,
    input_type=protos_dot_plugin_dot_common__pb2._SERVICEINPUT,
    output_type=_SERVICEOUTPUTLIBRARYTYPE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='IsUsed',
    full_name='proto.LibraryService.IsUsed',
    index=1,
    containing_service=None,
    input_type=protos_dot_plugin_dot_common__pb2._SERVICEINPUT,
    output_type=protos_dot_plugin_dot_common__pb2._SERVICEOUTPUTBOOL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PercentOfUsed',
    full_name='proto.LibraryService.PercentOfUsed',
    index=2,
    containing_service=None,
    input_type=protos_dot_plugin_dot_common__pb2._SERVICEINPUT,
    output_type=protos_dot_plugin_dot_common__pb2._SERVICEOUTPUTFLOAT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LIBRARYSERVICE)

DESCRIPTOR.services_by_name['LibraryService'] = _LIBRARYSERVICE

# @@protoc_insertion_point(module_scope)
