# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos.plugin import common_pb2 as protos_dot_plugin_dot_common__pb2
from protos.plugin import library_pb2 as protos_dot_plugin_dot_library__pb2


class LibraryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Detect = channel.unary_unary(
                '/proto.LibraryService/Detect',
                request_serializer=protos_dot_plugin_dot_common__pb2.ServiceInput.SerializeToString,
                response_deserializer=protos_dot_plugin_dot_library__pb2.ServiceOutputLibraryType.FromString,
                )
        self.IsUsed = channel.unary_unary(
                '/proto.LibraryService/IsUsed',
                request_serializer=protos_dot_plugin_dot_common__pb2.ServiceInput.SerializeToString,
                response_deserializer=protos_dot_plugin_dot_common__pb2.ServiceOutputBool.FromString,
                )
        self.PercentOfUsed = channel.unary_unary(
                '/proto.LibraryService/PercentOfUsed',
                request_serializer=protos_dot_plugin_dot_common__pb2.ServiceInput.SerializeToString,
                response_deserializer=protos_dot_plugin_dot_common__pb2.ServiceOutputFloat.FromString,
                )


class LibraryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Detect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsUsed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PercentOfUsed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LibraryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Detect': grpc.unary_unary_rpc_method_handler(
                    servicer.Detect,
                    request_deserializer=protos_dot_plugin_dot_common__pb2.ServiceInput.FromString,
                    response_serializer=protos_dot_plugin_dot_library__pb2.ServiceOutputLibraryType.SerializeToString,
            ),
            'IsUsed': grpc.unary_unary_rpc_method_handler(
                    servicer.IsUsed,
                    request_deserializer=protos_dot_plugin_dot_common__pb2.ServiceInput.FromString,
                    response_serializer=protos_dot_plugin_dot_common__pb2.ServiceOutputBool.SerializeToString,
            ),
            'PercentOfUsed': grpc.unary_unary_rpc_method_handler(
                    servicer.PercentOfUsed,
                    request_deserializer=protos_dot_plugin_dot_common__pb2.ServiceInput.FromString,
                    response_serializer=protos_dot_plugin_dot_common__pb2.ServiceOutputFloat.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.LibraryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LibraryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Detect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.LibraryService/Detect',
            protos_dot_plugin_dot_common__pb2.ServiceInput.SerializeToString,
            protos_dot_plugin_dot_library__pb2.ServiceOutputLibraryType.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IsUsed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.LibraryService/IsUsed',
            protos_dot_plugin_dot_common__pb2.ServiceInput.SerializeToString,
            protos_dot_plugin_dot_common__pb2.ServiceOutputBool.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PercentOfUsed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.LibraryService/PercentOfUsed',
            protos_dot_plugin_dot_common__pb2.ServiceInput.SerializeToString,
            protos_dot_plugin_dot_common__pb2.ServiceOutputFloat.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
