// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        (unknown)
// source: outputs/global/migrationCommandfs.proto

package protos

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MigrationCommandsOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// check MigrationCommand
	Used bool `protobuf:"varint,1,opt,name=used,proto3" json:"used,omitempty"`
	// list of all MigrationCommand
	MigrationCommand []*MigrationCommand `protobuf:"bytes,2,rep,name=migrationCommand,proto3" json:"migrationCommand,omitempty"`
}

func (x *MigrationCommandsOutput) Reset() {
	*x = MigrationCommandsOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outputs_global_migrationCommandfs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MigrationCommandsOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationCommandsOutput) ProtoMessage() {}

func (x *MigrationCommandsOutput) ProtoReflect() protoreflect.Message {
	mi := &file_outputs_global_migrationCommandfs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationCommandsOutput.ProtoReflect.Descriptor instead.
func (*MigrationCommandsOutput) Descriptor() ([]byte, []int) {
	return file_outputs_global_migrationCommandfs_proto_rawDescGZIP(), []int{0}
}

func (x *MigrationCommandsOutput) GetUsed() bool {
	if x != nil {
		return x.Used
	}
	return false
}

func (x *MigrationCommandsOutput) GetMigrationCommand() []*MigrationCommand {
	if x != nil {
		return x.MigrationCommand
	}
	return nil
}

type MigrationCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//  name of MigrationCommand
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	//  version of MigrationCommand
	Args []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *MigrationCommand) Reset() {
	*x = MigrationCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outputs_global_migrationCommandfs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MigrationCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrationCommand) ProtoMessage() {}

func (x *MigrationCommand) ProtoReflect() protoreflect.Message {
	mi := &file_outputs_global_migrationCommandfs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrationCommand.ProtoReflect.Descriptor instead.
func (*MigrationCommand) Descriptor() ([]byte, []int) {
	return file_outputs_global_migrationCommandfs_proto_rawDescGZIP(), []int{1}
}

func (x *MigrationCommand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MigrationCommand) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

var File_outputs_global_migrationCommandfs_proto protoreflect.FileDescriptor

var file_outputs_global_migrationCommandfs_proto_rawDesc = []byte{
	0x0a, 0x27, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x2f, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c,
	0x2f, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x66, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6c, 0x0a, 0x17, 0x4d, 0x69, 0x67,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x04, 0x75, 0x73, 0x65, 0x64, 0x12, 0x3d, 0x0a, 0x10, 0x6d, 0x69, 0x67, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x10, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x3a, 0x0a, 0x10, 0x4d, 0x69, 0x67, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61,
	0x72, 0x67, 0x73, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_outputs_global_migrationCommandfs_proto_rawDescOnce sync.Once
	file_outputs_global_migrationCommandfs_proto_rawDescData = file_outputs_global_migrationCommandfs_proto_rawDesc
)

func file_outputs_global_migrationCommandfs_proto_rawDescGZIP() []byte {
	file_outputs_global_migrationCommandfs_proto_rawDescOnce.Do(func() {
		file_outputs_global_migrationCommandfs_proto_rawDescData = protoimpl.X.CompressGZIP(file_outputs_global_migrationCommandfs_proto_rawDescData)
	})
	return file_outputs_global_migrationCommandfs_proto_rawDescData
}

var file_outputs_global_migrationCommandfs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_outputs_global_migrationCommandfs_proto_goTypes = []interface{}{
	(*MigrationCommandsOutput)(nil), // 0: MigrationCommandsOutput
	(*MigrationCommand)(nil),        // 1: MigrationCommand
}
var file_outputs_global_migrationCommandfs_proto_depIdxs = []int32{
	1, // 0: MigrationCommandsOutput.migrationCommand:type_name -> MigrationCommand
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_outputs_global_migrationCommandfs_proto_init() }
func file_outputs_global_migrationCommandfs_proto_init() {
	if File_outputs_global_migrationCommandfs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_outputs_global_migrationCommandfs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MigrationCommandsOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_outputs_global_migrationCommandfs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MigrationCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_outputs_global_migrationCommandfs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_outputs_global_migrationCommandfs_proto_goTypes,
		DependencyIndexes: file_outputs_global_migrationCommandfs_proto_depIdxs,
		MessageInfos:      file_outputs_global_migrationCommandfs_proto_msgTypes,
	}.Build()
	File_outputs_global_migrationCommandfs_proto = out.File
	file_outputs_global_migrationCommandfs_proto_rawDesc = nil
	file_outputs_global_migrationCommandfs_proto_goTypes = nil
	file_outputs_global_migrationCommandfs_proto_depIdxs = nil
}
