// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package plugin

import (
	helpers "code-analyser/protos/pb/helpers"
	languageSpecific "code-analyser/protos/pb/output/languageSpecific"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BuildDirectoryClient is the client API for BuildDirectory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BuildDirectoryClient interface {
	Detect(ctx context.Context, in *helpers.Input, opts ...grpc.CallOption) (*languageSpecific.BuildDirectoryOutput, error)
}

type buildDirectoryClient struct {
	cc grpc.ClientConnInterface
}

func NewBuildDirectoryClient(cc grpc.ClientConnInterface) BuildDirectoryClient {
	return &buildDirectoryClient{cc}
}

func (c *buildDirectoryClient) Detect(ctx context.Context, in *helpers.Input, opts ...grpc.CallOption) (*languageSpecific.BuildDirectoryOutput, error) {
	out := new(languageSpecific.BuildDirectoryOutput)
	err := c.cc.Invoke(ctx, "/proto.BuildDirectory/Detect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BuildDirectoryServer is the server API for BuildDirectory service.
// All implementations should embed UnimplementedBuildDirectoryServer
// for forward compatibility
type BuildDirectoryServer interface {
	Detect(context.Context, *helpers.Input) (*languageSpecific.BuildDirectoryOutput, error)
}

// UnimplementedBuildDirectoryServer should be embedded to have forward compatible implementations.
type UnimplementedBuildDirectoryServer struct {
}

func (UnimplementedBuildDirectoryServer) Detect(context.Context, *helpers.Input) (*languageSpecific.BuildDirectoryOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Detect not implemented")
}

// UnsafeBuildDirectoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BuildDirectoryServer will
// result in compilation errors.
type UnsafeBuildDirectoryServer interface {
	mustEmbedUnimplementedBuildDirectoryServer()
}

func RegisterBuildDirectoryServer(s grpc.ServiceRegistrar, srv BuildDirectoryServer) {
	s.RegisterService(&BuildDirectory_ServiceDesc, srv)
}

func _BuildDirectory_Detect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(helpers.Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildDirectoryServer).Detect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BuildDirectory/Detect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildDirectoryServer).Detect(ctx, req.(*helpers.Input))
	}
	return interceptor(ctx, in, info, handler)
}

// BuildDirectory_ServiceDesc is the grpc.ServiceDesc for BuildDirectory service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BuildDirectory_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.BuildDirectory",
	HandlerType: (*BuildDirectoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Detect",
			Handler:    _BuildDirectory_Detect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/plugin/buildDirectory.proto",
}
