// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package plugin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CommandsServiceClient is the client API for CommandsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommandsServiceClient interface {
	DetectBuildCommands(ctx context.Context, in *ServiceCommandsInput, opts ...grpc.CallOption) (*ServiceOutputDetectBuildCommands, error)
	DetectStartUpCommands(ctx context.Context, in *ServiceCommandsInput, opts ...grpc.CallOption) (*ServiceOutputStartUpCommands, error)
	DetectSeedCommands(ctx context.Context, in *ServiceCommandsInput, opts ...grpc.CallOption) (*ServiceOutputSeedCommands, error)
	DetectMigrationCommands(ctx context.Context, in *ServiceCommandsInput, opts ...grpc.CallOption) (*ServiceMigrationCommands, error)
	DetectAdHocScripts(ctx context.Context, in *ServiceCommandsInput, opts ...grpc.CallOption) (*ServiceAdHocScripts, error)
}

type commandsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommandsServiceClient(cc grpc.ClientConnInterface) CommandsServiceClient {
	return &commandsServiceClient{cc}
}

func (c *commandsServiceClient) DetectBuildCommands(ctx context.Context, in *ServiceCommandsInput, opts ...grpc.CallOption) (*ServiceOutputDetectBuildCommands, error) {
	out := new(ServiceOutputDetectBuildCommands)
	err := c.cc.Invoke(ctx, "/proto.CommandsService/DetectBuildCommands", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandsServiceClient) DetectStartUpCommands(ctx context.Context, in *ServiceCommandsInput, opts ...grpc.CallOption) (*ServiceOutputStartUpCommands, error) {
	out := new(ServiceOutputStartUpCommands)
	err := c.cc.Invoke(ctx, "/proto.CommandsService/DetectStartUpCommands", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandsServiceClient) DetectSeedCommands(ctx context.Context, in *ServiceCommandsInput, opts ...grpc.CallOption) (*ServiceOutputSeedCommands, error) {
	out := new(ServiceOutputSeedCommands)
	err := c.cc.Invoke(ctx, "/proto.CommandsService/DetectSeedCommands", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandsServiceClient) DetectMigrationCommands(ctx context.Context, in *ServiceCommandsInput, opts ...grpc.CallOption) (*ServiceMigrationCommands, error) {
	out := new(ServiceMigrationCommands)
	err := c.cc.Invoke(ctx, "/proto.CommandsService/DetectMigrationCommands", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandsServiceClient) DetectAdHocScripts(ctx context.Context, in *ServiceCommandsInput, opts ...grpc.CallOption) (*ServiceAdHocScripts, error) {
	out := new(ServiceAdHocScripts)
	err := c.cc.Invoke(ctx, "/proto.CommandsService/DetectAdHocScripts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommandsServiceServer is the server API for CommandsService service.
// All implementations should embed UnimplementedCommandsServiceServer
// for forward compatibility
type CommandsServiceServer interface {
	DetectBuildCommands(context.Context, *ServiceCommandsInput) (*ServiceOutputDetectBuildCommands, error)
	DetectStartUpCommands(context.Context, *ServiceCommandsInput) (*ServiceOutputStartUpCommands, error)
	DetectSeedCommands(context.Context, *ServiceCommandsInput) (*ServiceOutputSeedCommands, error)
	DetectMigrationCommands(context.Context, *ServiceCommandsInput) (*ServiceMigrationCommands, error)
	DetectAdHocScripts(context.Context, *ServiceCommandsInput) (*ServiceAdHocScripts, error)
}

// UnimplementedCommandsServiceServer should be embedded to have forward compatible implementations.
type UnimplementedCommandsServiceServer struct {
}

func (UnimplementedCommandsServiceServer) DetectBuildCommands(context.Context, *ServiceCommandsInput) (*ServiceOutputDetectBuildCommands, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DetectBuildCommands not implemented")
}
func (UnimplementedCommandsServiceServer) DetectStartUpCommands(context.Context, *ServiceCommandsInput) (*ServiceOutputStartUpCommands, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DetectStartUpCommands not implemented")
}
func (UnimplementedCommandsServiceServer) DetectSeedCommands(context.Context, *ServiceCommandsInput) (*ServiceOutputSeedCommands, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DetectSeedCommands not implemented")
}
func (UnimplementedCommandsServiceServer) DetectMigrationCommands(context.Context, *ServiceCommandsInput) (*ServiceMigrationCommands, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DetectMigrationCommands not implemented")
}
func (UnimplementedCommandsServiceServer) DetectAdHocScripts(context.Context, *ServiceCommandsInput) (*ServiceAdHocScripts, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DetectAdHocScripts not implemented")
}

// UnsafeCommandsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommandsServiceServer will
// result in compilation errors.
type UnsafeCommandsServiceServer interface {
	mustEmbedUnimplementedCommandsServiceServer()
}

func RegisterCommandsServiceServer(s grpc.ServiceRegistrar, srv CommandsServiceServer) {
	s.RegisterService(&CommandsService_ServiceDesc, srv)
}

func _CommandsService_DetectBuildCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceCommandsInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandsServiceServer).DetectBuildCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CommandsService/DetectBuildCommands",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandsServiceServer).DetectBuildCommands(ctx, req.(*ServiceCommandsInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandsService_DetectStartUpCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceCommandsInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandsServiceServer).DetectStartUpCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CommandsService/DetectStartUpCommands",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandsServiceServer).DetectStartUpCommands(ctx, req.(*ServiceCommandsInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandsService_DetectSeedCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceCommandsInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandsServiceServer).DetectSeedCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CommandsService/DetectSeedCommands",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandsServiceServer).DetectSeedCommands(ctx, req.(*ServiceCommandsInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandsService_DetectMigrationCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceCommandsInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandsServiceServer).DetectMigrationCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CommandsService/DetectMigrationCommands",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandsServiceServer).DetectMigrationCommands(ctx, req.(*ServiceCommandsInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandsService_DetectAdHocScripts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceCommandsInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandsServiceServer).DetectAdHocScripts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CommandsService/DetectAdHocScripts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandsServiceServer).DetectAdHocScripts(ctx, req.(*ServiceCommandsInput))
	}
	return interceptor(ctx, in, info, handler)
}

// CommandsService_ServiceDesc is the grpc.ServiceDesc for CommandsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommandsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CommandsService",
	HandlerType: (*CommandsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DetectBuildCommands",
			Handler:    _CommandsService_DetectBuildCommands_Handler,
		},
		{
			MethodName: "DetectStartUpCommands",
			Handler:    _CommandsService_DetectStartUpCommands_Handler,
		},
		{
			MethodName: "DetectSeedCommands",
			Handler:    _CommandsService_DetectSeedCommands_Handler,
		},
		{
			MethodName: "DetectMigrationCommands",
			Handler:    _CommandsService_DetectMigrationCommands_Handler,
		},
		{
			MethodName: "DetectAdHocScripts",
			Handler:    _CommandsService_DetectAdHocScripts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/plugin/commands.proto",
}
