// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package plugin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DependenciesClient is the client API for Dependencies service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DependenciesClient interface {
	GetDependencies(ctx context.Context, in *Input, opts ...grpc.CallOption) (*StringMapOutput, error)
}

type dependenciesClient struct {
	cc grpc.ClientConnInterface
}

func NewDependenciesClient(cc grpc.ClientConnInterface) DependenciesClient {
	return &dependenciesClient{cc}
}

func (c *dependenciesClient) GetDependencies(ctx context.Context, in *Input, opts ...grpc.CallOption) (*StringMapOutput, error) {
	out := new(StringMapOutput)
	err := c.cc.Invoke(ctx, "/proto.Dependencies/GetDependencies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DependenciesServer is the server API for Dependencies service.
// All implementations should embed UnimplementedDependenciesServer
// for forward compatibility
type DependenciesServer interface {
	GetDependencies(context.Context, *Input) (*StringMapOutput, error)
}

// UnimplementedDependenciesServer should be embedded to have forward compatible implementations.
type UnimplementedDependenciesServer struct {
}

func (UnimplementedDependenciesServer) GetDependencies(context.Context, *Input) (*StringMapOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDependencies not implemented")
}

// UnsafeDependenciesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DependenciesServer will
// result in compilation errors.
type UnsafeDependenciesServer interface {
	mustEmbedUnimplementedDependenciesServer()
}

func RegisterDependenciesServer(s grpc.ServiceRegistrar, srv DependenciesServer) {
	s.RegisterService(&Dependencies_ServiceDesc, srv)
}

func _Dependencies_GetDependencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DependenciesServer).GetDependencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dependencies/GetDependencies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DependenciesServer).GetDependencies(ctx, req.(*Input))
	}
	return interceptor(ctx, in, info, handler)
}

// Dependencies_ServiceDesc is the grpc.ServiceDesc for Dependencies service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Dependencies_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Dependencies",
	HandlerType: (*DependenciesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDependencies",
			Handler:    _Dependencies_GetDependencies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/plugin/dependencies.proto",
}
