// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package plugin

import (
	helpers "code-analyser/protos/pb/helpers"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DetectRuntimeClient is the client API for DetectRuntime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DetectRuntimeClient interface {
	Detect(ctx context.Context, in *helpers.StringInput, opts ...grpc.CallOption) (*helpers.StringOutput, error)
}

type detectRuntimeClient struct {
	cc grpc.ClientConnInterface
}

func NewDetectRuntimeClient(cc grpc.ClientConnInterface) DetectRuntimeClient {
	return &detectRuntimeClient{cc}
}

func (c *detectRuntimeClient) Detect(ctx context.Context, in *helpers.StringInput, opts ...grpc.CallOption) (*helpers.StringOutput, error) {
	out := new(helpers.StringOutput)
	err := c.cc.Invoke(ctx, "/proto.DetectRuntime/Detect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DetectRuntimeServer is the server API for DetectRuntime service.
// All implementations should embed UnimplementedDetectRuntimeServer
// for forward compatibility
type DetectRuntimeServer interface {
	Detect(context.Context, *helpers.StringInput) (*helpers.StringOutput, error)
}

// UnimplementedDetectRuntimeServer should be embedded to have forward compatible implementations.
type UnimplementedDetectRuntimeServer struct {
}

func (UnimplementedDetectRuntimeServer) Detect(context.Context, *helpers.StringInput) (*helpers.StringOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Detect not implemented")
}

// UnsafeDetectRuntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DetectRuntimeServer will
// result in compilation errors.
type UnsafeDetectRuntimeServer interface {
	mustEmbedUnimplementedDetectRuntimeServer()
}

func RegisterDetectRuntimeServer(s grpc.ServiceRegistrar, srv DetectRuntimeServer) {
	s.RegisterService(&DetectRuntime_ServiceDesc, srv)
}

func _DetectRuntime_Detect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(helpers.StringInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectRuntimeServer).Detect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DetectRuntime/Detect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectRuntimeServer).Detect(ctx, req.(*helpers.StringInput))
	}
	return interceptor(ctx, in, info, handler)
}

// DetectRuntime_ServiceDesc is the grpc.ServiceDesc for DetectRuntime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DetectRuntime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DetectRuntime",
	HandlerType: (*DetectRuntimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Detect",
			Handler:    _DetectRuntime_Detect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/plugin/detectRuntime.proto",
}
