// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package plugin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FrameworkServiceClient is the client API for FrameworkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FrameworkServiceClient interface {
	Detect(ctx context.Context, in *ServiceInput, opts ...grpc.CallOption) (*ServiceOutputBool, error)
	IsFrameworkUsed(ctx context.Context, in *ServiceInput, opts ...grpc.CallOption) (*ServiceOutputBool, error)
	PercentOfFrameworkUsed(ctx context.Context, in *ServiceInput, opts ...grpc.CallOption) (*ServiceOutputFloat, error)
}

type frameworkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFrameworkServiceClient(cc grpc.ClientConnInterface) FrameworkServiceClient {
	return &frameworkServiceClient{cc}
}

func (c *frameworkServiceClient) Detect(ctx context.Context, in *ServiceInput, opts ...grpc.CallOption) (*ServiceOutputBool, error) {
	out := new(ServiceOutputBool)
	err := c.cc.Invoke(ctx, "/proto.FrameworkService/Detect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frameworkServiceClient) IsFrameworkUsed(ctx context.Context, in *ServiceInput, opts ...grpc.CallOption) (*ServiceOutputBool, error) {
	out := new(ServiceOutputBool)
	err := c.cc.Invoke(ctx, "/proto.FrameworkService/IsFrameworkUsed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frameworkServiceClient) PercentOfFrameworkUsed(ctx context.Context, in *ServiceInput, opts ...grpc.CallOption) (*ServiceOutputFloat, error) {
	out := new(ServiceOutputFloat)
	err := c.cc.Invoke(ctx, "/proto.FrameworkService/PercentOfFrameworkUsed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FrameworkServiceServer is the server API for FrameworkService service.
// All implementations should embed UnimplementedFrameworkServiceServer
// for forward compatibility
type FrameworkServiceServer interface {
	Detect(context.Context, *ServiceInput) (*ServiceOutputBool, error)
	IsFrameworkUsed(context.Context, *ServiceInput) (*ServiceOutputBool, error)
	PercentOfFrameworkUsed(context.Context, *ServiceInput) (*ServiceOutputFloat, error)
}

// UnimplementedFrameworkServiceServer should be embedded to have forward compatible implementations.
type UnimplementedFrameworkServiceServer struct {
}

func (UnimplementedFrameworkServiceServer) Detect(context.Context, *ServiceInput) (*ServiceOutputBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Detect not implemented")
}
func (UnimplementedFrameworkServiceServer) IsFrameworkUsed(context.Context, *ServiceInput) (*ServiceOutputBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsFrameworkUsed not implemented")
}
func (UnimplementedFrameworkServiceServer) PercentOfFrameworkUsed(context.Context, *ServiceInput) (*ServiceOutputFloat, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PercentOfFrameworkUsed not implemented")
}

// UnsafeFrameworkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FrameworkServiceServer will
// result in compilation errors.
type UnsafeFrameworkServiceServer interface {
	mustEmbedUnimplementedFrameworkServiceServer()
}

func RegisterFrameworkServiceServer(s grpc.ServiceRegistrar, srv FrameworkServiceServer) {
	s.RegisterService(&FrameworkService_ServiceDesc, srv)
}

func _FrameworkService_Detect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrameworkServiceServer).Detect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.FrameworkService/Detect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrameworkServiceServer).Detect(ctx, req.(*ServiceInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrameworkService_IsFrameworkUsed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrameworkServiceServer).IsFrameworkUsed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.FrameworkService/IsFrameworkUsed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrameworkServiceServer).IsFrameworkUsed(ctx, req.(*ServiceInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrameworkService_PercentOfFrameworkUsed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrameworkServiceServer).PercentOfFrameworkUsed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.FrameworkService/PercentOfFrameworkUsed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrameworkServiceServer).PercentOfFrameworkUsed(ctx, req.(*ServiceInput))
	}
	return interceptor(ctx, in, info, handler)
}

// FrameworkService_ServiceDesc is the grpc.ServiceDesc for FrameworkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FrameworkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.FrameworkService",
	HandlerType: (*FrameworkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Detect",
			Handler:    _FrameworkService_Detect_Handler,
		},
		{
			MethodName: "IsFrameworkUsed",
			Handler:    _FrameworkService_IsFrameworkUsed_Handler,
		},
		{
			MethodName: "PercentOfFrameworkUsed",
			Handler:    _FrameworkService_PercentOfFrameworkUsed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/plugin/framework.proto",
}
