// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: protos/plugin/library.proto

package plugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LibraryType_Type int32

const (
	LibraryType_REPLACED LibraryType_Type = 0
	LibraryType_EXTERNAL LibraryType_Type = 1
)

// Enum value maps for LibraryType_Type.
var (
	LibraryType_Type_name = map[int32]string{
		0: "REPLACED",
		1: "EXTERNAL",
	}
	LibraryType_Type_value = map[string]int32{
		"REPLACED": 0,
		"EXTERNAL": 1,
	}
)

func (x LibraryType_Type) Enum() *LibraryType_Type {
	p := new(LibraryType_Type)
	*p = x
	return p
}

func (x LibraryType_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LibraryType_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_plugin_library_proto_enumTypes[0].Descriptor()
}

func (LibraryType_Type) Type() protoreflect.EnumType {
	return &file_protos_plugin_library_proto_enumTypes[0]
}

func (x LibraryType_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LibraryType_Type.Descriptor instead.
func (LibraryType_Type) EnumDescriptor() ([]byte, []int) {
	return file_protos_plugin_library_proto_rawDescGZIP(), []int{0, 0}
}

type LibraryType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value bool             `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Type  LibraryType_Type `protobuf:"varint,3,opt,name=type,proto3,enum=proto.LibraryType_Type" json:"type,omitempty"`
	Error *Error           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *LibraryType) Reset() {
	*x = LibraryType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_plugin_library_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LibraryType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LibraryType) ProtoMessage() {}

func (x *LibraryType) ProtoReflect() protoreflect.Message {
	mi := &file_protos_plugin_library_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LibraryType.ProtoReflect.Descriptor instead.
func (*LibraryType) Descriptor() ([]byte, []int) {
	return file_protos_plugin_library_proto_rawDescGZIP(), []int{0}
}

func (x *LibraryType) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

func (x *LibraryType) GetType() LibraryType_Type {
	if x != nil {
		return x.Type
	}
	return LibraryType_REPLACED
}

func (x *LibraryType) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_protos_plugin_library_proto protoreflect.FileDescriptor

var file_protos_plugin_library_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f,
	0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x98, 0x01, 0x0a, 0x0b, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x62,
	0x72, 0x61, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x22, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0c, 0x0a, 0x08, 0x52, 0x45, 0x50, 0x4c, 0x41, 0x43, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0c, 0x0a,
	0x08, 0x45, 0x58, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x10, 0x01, 0x32, 0x93, 0x01, 0x0a, 0x07,
	0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x12, 0x2a, 0x0a, 0x06, 0x44, 0x65, 0x74, 0x65, 0x63,
	0x74, 0x12, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a,
	0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x49, 0x73, 0x55, 0x73, 0x65, 0x64, 0x12, 0x0c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x11, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x31,
	0x0a, 0x0d, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x4f, 0x66, 0x55, 0x73, 0x65, 0x64, 0x12,
	0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x12, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x42, 0x20, 0x5a, 0x1e, 0x63, 0x6f, 0x64, 0x65, 0x2d, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73,
	0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_plugin_library_proto_rawDescOnce sync.Once
	file_protos_plugin_library_proto_rawDescData = file_protos_plugin_library_proto_rawDesc
)

func file_protos_plugin_library_proto_rawDescGZIP() []byte {
	file_protos_plugin_library_proto_rawDescOnce.Do(func() {
		file_protos_plugin_library_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_plugin_library_proto_rawDescData)
	})
	return file_protos_plugin_library_proto_rawDescData
}

var file_protos_plugin_library_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_plugin_library_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_plugin_library_proto_goTypes = []interface{}{
	(LibraryType_Type)(0), // 0: proto.LibraryType.Type
	(*LibraryType)(nil),   // 1: proto.LibraryType
	(*Error)(nil),         // 2: proto.Error
	(*Input)(nil),         // 3: proto.Input
	(*BoolOutput)(nil),    // 4: proto.BoolOutput
	(*FloatOutput)(nil),   // 5: proto.FloatOutput
}
var file_protos_plugin_library_proto_depIdxs = []int32{
	0, // 0: proto.LibraryType.type:type_name -> proto.LibraryType.Type
	2, // 1: proto.LibraryType.error:type_name -> proto.Error
	3, // 2: proto.Library.Detect:input_type -> proto.Input
	3, // 3: proto.Library.IsUsed:input_type -> proto.Input
	3, // 4: proto.Library.PercentOfUsed:input_type -> proto.Input
	1, // 5: proto.Library.Detect:output_type -> proto.LibraryType
	4, // 6: proto.Library.IsUsed:output_type -> proto.BoolOutput
	5, // 7: proto.Library.PercentOfUsed:output_type -> proto.FloatOutput
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_plugin_library_proto_init() }
func file_protos_plugin_library_proto_init() {
	if File_protos_plugin_library_proto != nil {
		return
	}
	file_protos_plugin_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protos_plugin_library_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LibraryType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_plugin_library_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_plugin_library_proto_goTypes,
		DependencyIndexes: file_protos_plugin_library_proto_depIdxs,
		EnumInfos:         file_protos_plugin_library_proto_enumTypes,
		MessageInfos:      file_protos_plugin_library_proto_msgTypes,
	}.Build()
	File_protos_plugin_library_proto = out.File
	file_protos_plugin_library_proto_rawDesc = nil
	file_protos_plugin_library_proto_goTypes = nil
	file_protos_plugin_library_proto_depIdxs = nil
}
