// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package plugin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MakeFileClient is the client API for MakeFile service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MakeFileClient interface {
	Detect(ctx context.Context, in *StringInput, opts ...grpc.CallOption) (*MakeFileOutput, error)
}

type makeFileClient struct {
	cc grpc.ClientConnInterface
}

func NewMakeFileClient(cc grpc.ClientConnInterface) MakeFileClient {
	return &makeFileClient{cc}
}

func (c *makeFileClient) Detect(ctx context.Context, in *StringInput, opts ...grpc.CallOption) (*MakeFileOutput, error) {
	out := new(MakeFileOutput)
	err := c.cc.Invoke(ctx, "/proto.MakeFile/Detect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MakeFileServer is the server API for MakeFile service.
// All implementations should embed UnimplementedMakeFileServer
// for forward compatibility
type MakeFileServer interface {
	Detect(context.Context, *StringInput) (*MakeFileOutput, error)
}

// UnimplementedMakeFileServer should be embedded to have forward compatible implementations.
type UnimplementedMakeFileServer struct {
}

func (UnimplementedMakeFileServer) Detect(context.Context, *StringInput) (*MakeFileOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Detect not implemented")
}

// UnsafeMakeFileServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MakeFileServer will
// result in compilation errors.
type UnsafeMakeFileServer interface {
	mustEmbedUnimplementedMakeFileServer()
}

func RegisterMakeFileServer(s grpc.ServiceRegistrar, srv MakeFileServer) {
	s.RegisterService(&MakeFile_ServiceDesc, srv)
}

func _MakeFile_Detect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MakeFileServer).Detect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MakeFile/Detect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MakeFileServer).Detect(ctx, req.(*StringInput))
	}
	return interceptor(ctx, in, info, handler)
}

// MakeFile_ServiceDesc is the grpc.ServiceDesc for MakeFile service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MakeFile_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MakeFile",
	HandlerType: (*MakeFileServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Detect",
			Handler:    _MakeFile_Detect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/plugin/makeFile.proto",
}
