// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package plugin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MakeFileServiceClient is the client API for MakeFileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MakeFileServiceClient interface {
	Detect(ctx context.Context, in *ServiceInputString, opts ...grpc.CallOption) (*ServiceOutputMakeFile, error)
}

type makeFileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMakeFileServiceClient(cc grpc.ClientConnInterface) MakeFileServiceClient {
	return &makeFileServiceClient{cc}
}

func (c *makeFileServiceClient) Detect(ctx context.Context, in *ServiceInputString, opts ...grpc.CallOption) (*ServiceOutputMakeFile, error) {
	out := new(ServiceOutputMakeFile)
	err := c.cc.Invoke(ctx, "/proto.MakeFileService/Detect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MakeFileServiceServer is the server API for MakeFileService service.
// All implementations should embed UnimplementedMakeFileServiceServer
// for forward compatibility
type MakeFileServiceServer interface {
	Detect(context.Context, *ServiceInputString) (*ServiceOutputMakeFile, error)
}

// UnimplementedMakeFileServiceServer should be embedded to have forward compatible implementations.
type UnimplementedMakeFileServiceServer struct {
}

func (UnimplementedMakeFileServiceServer) Detect(context.Context, *ServiceInputString) (*ServiceOutputMakeFile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Detect not implemented")
}

// UnsafeMakeFileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MakeFileServiceServer will
// result in compilation errors.
type UnsafeMakeFileServiceServer interface {
	mustEmbedUnimplementedMakeFileServiceServer()
}

func RegisterMakeFileServiceServer(s grpc.ServiceRegistrar, srv MakeFileServiceServer) {
	s.RegisterService(&MakeFileService_ServiceDesc, srv)
}

func _MakeFileService_Detect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceInputString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MakeFileServiceServer).Detect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MakeFileService/Detect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MakeFileServiceServer).Detect(ctx, req.(*ServiceInputString))
	}
	return interceptor(ctx, in, info, handler)
}

// MakeFileService_ServiceDesc is the grpc.ServiceDesc for MakeFileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MakeFileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MakeFileService",
	HandlerType: (*MakeFileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Detect",
			Handler:    _MakeFileService_Detect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/plugin/makeFile.proto",
}
