// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package plugin

import (
	helpers "code-analyser/protos/pb/helpers"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OrmClient is the client API for Orm service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrmClient interface {
	Detect(ctx context.Context, in *helpers.Input, opts ...grpc.CallOption) (*OrmOutput, error)
	IsUsed(ctx context.Context, in *helpers.Input, opts ...grpc.CallOption) (*helpers.BoolOutput, error)
	PercentOfUsed(ctx context.Context, in *helpers.Input, opts ...grpc.CallOption) (*helpers.FloatOutput, error)
}

type ormClient struct {
	cc grpc.ClientConnInterface
}

func NewOrmClient(cc grpc.ClientConnInterface) OrmClient {
	return &ormClient{cc}
}

func (c *ormClient) Detect(ctx context.Context, in *helpers.Input, opts ...grpc.CallOption) (*OrmOutput, error) {
	out := new(OrmOutput)
	err := c.cc.Invoke(ctx, "/proto.Orm/Detect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ormClient) IsUsed(ctx context.Context, in *helpers.Input, opts ...grpc.CallOption) (*helpers.BoolOutput, error) {
	out := new(helpers.BoolOutput)
	err := c.cc.Invoke(ctx, "/proto.Orm/IsUsed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ormClient) PercentOfUsed(ctx context.Context, in *helpers.Input, opts ...grpc.CallOption) (*helpers.FloatOutput, error) {
	out := new(helpers.FloatOutput)
	err := c.cc.Invoke(ctx, "/proto.Orm/PercentOfUsed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrmServer is the server API for Orm service.
// All implementations should embed UnimplementedOrmServer
// for forward compatibility
type OrmServer interface {
	Detect(context.Context, *helpers.Input) (*OrmOutput, error)
	IsUsed(context.Context, *helpers.Input) (*helpers.BoolOutput, error)
	PercentOfUsed(context.Context, *helpers.Input) (*helpers.FloatOutput, error)
}

// UnimplementedOrmServer should be embedded to have forward compatible implementations.
type UnimplementedOrmServer struct {
}

func (UnimplementedOrmServer) Detect(context.Context, *helpers.Input) (*OrmOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Detect not implemented")
}
func (UnimplementedOrmServer) IsUsed(context.Context, *helpers.Input) (*helpers.BoolOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsUsed not implemented")
}
func (UnimplementedOrmServer) PercentOfUsed(context.Context, *helpers.Input) (*helpers.FloatOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PercentOfUsed not implemented")
}

// UnsafeOrmServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrmServer will
// result in compilation errors.
type UnsafeOrmServer interface {
	mustEmbedUnimplementedOrmServer()
}

func RegisterOrmServer(s grpc.ServiceRegistrar, srv OrmServer) {
	s.RegisterService(&Orm_ServiceDesc, srv)
}

func _Orm_Detect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(helpers.Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrmServer).Detect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Orm/Detect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrmServer).Detect(ctx, req.(*helpers.Input))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orm_IsUsed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(helpers.Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrmServer).IsUsed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Orm/IsUsed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrmServer).IsUsed(ctx, req.(*helpers.Input))
	}
	return interceptor(ctx, in, info, handler)
}

func _Orm_PercentOfUsed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(helpers.Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrmServer).PercentOfUsed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Orm/PercentOfUsed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrmServer).PercentOfUsed(ctx, req.(*helpers.Input))
	}
	return interceptor(ctx, in, info, handler)
}

// Orm_ServiceDesc is the grpc.ServiceDesc for Orm service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Orm_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Orm",
	HandlerType: (*OrmServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Detect",
			Handler:    _Orm_Detect_Handler,
		},
		{
			MethodName: "IsUsed",
			Handler:    _Orm_IsUsed_Handler,
		},
		{
			MethodName: "PercentOfUsed",
			Handler:    _Orm_PercentOfUsed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/plugin/orm.proto",
}
