// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package plugin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProcFileServiceClient is the client API for ProcFileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProcFileServiceClient interface {
	Detect(ctx context.Context, in *ServiceInputString, opts ...grpc.CallOption) (*ServiceOutputProcFile, error)
}

type procFileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProcFileServiceClient(cc grpc.ClientConnInterface) ProcFileServiceClient {
	return &procFileServiceClient{cc}
}

func (c *procFileServiceClient) Detect(ctx context.Context, in *ServiceInputString, opts ...grpc.CallOption) (*ServiceOutputProcFile, error) {
	out := new(ServiceOutputProcFile)
	err := c.cc.Invoke(ctx, "/proto.ProcFileService/Detect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProcFileServiceServer is the server API for ProcFileService service.
// All implementations should embed UnimplementedProcFileServiceServer
// for forward compatibility
type ProcFileServiceServer interface {
	Detect(context.Context, *ServiceInputString) (*ServiceOutputProcFile, error)
}

// UnimplementedProcFileServiceServer should be embedded to have forward compatible implementations.
type UnimplementedProcFileServiceServer struct {
}

func (UnimplementedProcFileServiceServer) Detect(context.Context, *ServiceInputString) (*ServiceOutputProcFile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Detect not implemented")
}

// UnsafeProcFileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProcFileServiceServer will
// result in compilation errors.
type UnsafeProcFileServiceServer interface {
	mustEmbedUnimplementedProcFileServiceServer()
}

func RegisterProcFileServiceServer(s grpc.ServiceRegistrar, srv ProcFileServiceServer) {
	s.RegisterService(&ProcFileService_ServiceDesc, srv)
}

func _ProcFileService_Detect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceInputString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProcFileServiceServer).Detect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProcFileService/Detect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProcFileServiceServer).Detect(ctx, req.(*ServiceInputString))
	}
	return interceptor(ctx, in, info, handler)
}

// ProcFileService_ServiceDesc is the grpc.ServiceDesc for ProcFileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProcFileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ProcFileService",
	HandlerType: (*ProcFileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Detect",
			Handler:    _ProcFileService_Detect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/plugin/procfile.proto",
}
