// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: protos/plugin/test_case_commands.proto

package plugin

import (
	global "code-analyser/protos/pb/output/global"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestCommandOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Commands []*global.Command `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	Error    *Error            `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *TestCommandOutput) Reset() {
	*x = TestCommandOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_plugin_test_case_commands_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestCommandOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestCommandOutput) ProtoMessage() {}

func (x *TestCommandOutput) ProtoReflect() protoreflect.Message {
	mi := &file_protos_plugin_test_case_commands_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestCommandOutput.ProtoReflect.Descriptor instead.
func (*TestCommandOutput) Descriptor() ([]byte, []int) {
	return file_protos_plugin_test_case_commands_proto_rawDescGZIP(), []int{0}
}

func (x *TestCommandOutput) GetCommands() []*global.Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *TestCommandOutput) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_protos_plugin_test_case_commands_proto protoreflect.FileDescriptor

var file_protos_plugin_test_case_commands_proto_rawDesc = []byte{
	0x0a, 0x26, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f,
	0x74, 0x65, 0x73, 0x74, 0x5f, 0x63, 0x61, 0x73, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x22, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x2f, 0x67, 0x6c, 0x6f, 0x62, 0x61,
	0x6c, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x72, 0x0a, 0x11, 0x54, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x12, 0x39, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x2e, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x12,
	0x22, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x32, 0x44, 0x0a, 0x10, 0x54, 0x65, 0x73, 0x74, 0x43, 0x61, 0x73, 0x65, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x12, 0x30, 0x0a, 0x06, 0x44, 0x65, 0x74, 0x65, 0x63,
	0x74, 0x12, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a,
	0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x42, 0x20, 0x5a, 0x1e, 0x63, 0x6f, 0x64,
	0x65, 0x2d, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_protos_plugin_test_case_commands_proto_rawDescOnce sync.Once
	file_protos_plugin_test_case_commands_proto_rawDescData = file_protos_plugin_test_case_commands_proto_rawDesc
)

func file_protos_plugin_test_case_commands_proto_rawDescGZIP() []byte {
	file_protos_plugin_test_case_commands_proto_rawDescOnce.Do(func() {
		file_protos_plugin_test_case_commands_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_plugin_test_case_commands_proto_rawDescData)
	})
	return file_protos_plugin_test_case_commands_proto_rawDescData
}

var file_protos_plugin_test_case_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_plugin_test_case_commands_proto_goTypes = []interface{}{
	(*TestCommandOutput)(nil), // 0: proto.TestCommandOutput
	(*global.Command)(nil),    // 1: protos.output.global.Command
	(*Error)(nil),             // 2: proto.Error
	(*Input)(nil),             // 3: proto.Input
}
var file_protos_plugin_test_case_commands_proto_depIdxs = []int32{
	1, // 0: proto.TestCommandOutput.commands:type_name -> protos.output.global.Command
	2, // 1: proto.TestCommandOutput.error:type_name -> proto.Error
	3, // 2: proto.TestCaseCommands.Detect:input_type -> proto.Input
	0, // 3: proto.TestCaseCommands.Detect:output_type -> proto.TestCommandOutput
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_plugin_test_case_commands_proto_init() }
func file_protos_plugin_test_case_commands_proto_init() {
	if File_protos_plugin_test_case_commands_proto != nil {
		return
	}
	file_protos_plugin_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protos_plugin_test_case_commands_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestCommandOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_plugin_test_case_commands_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_plugin_test_case_commands_proto_goTypes,
		DependencyIndexes: file_protos_plugin_test_case_commands_proto_depIdxs,
		MessageInfos:      file_protos_plugin_test_case_commands_proto_msgTypes,
	}.Build()
	File_protos_plugin_test_case_commands_proto = out.File
	file_protos_plugin_test_case_commands_proto_rawDesc = nil
	file_protos_plugin_test_case_commands_proto_goTypes = nil
	file_protos_plugin_test_case_commands_proto_depIdxs = nil
}
