// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: protos/outputs/languageSpecific/orm.proto

package languageSpecific

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrmOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// check orm
	Used bool `protobuf:"varint,1,opt,name=used,proto3" json:"used,omitempty"`
	// list of all orms
	Orms []*ORM `protobuf:"bytes,2,rep,name=orms,proto3" json:"orms,omitempty"` // Should output database configuration details
}

func (x *OrmOutput) Reset() {
	*x = OrmOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_outputs_languageSpecific_orm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrmOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrmOutput) ProtoMessage() {}

func (x *OrmOutput) ProtoReflect() protoreflect.Message {
	mi := &file_protos_outputs_languageSpecific_orm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrmOutput.ProtoReflect.Descriptor instead.
func (*OrmOutput) Descriptor() ([]byte, []int) {
	return file_protos_outputs_languageSpecific_orm_proto_rawDescGZIP(), []int{0}
}

func (x *OrmOutput) GetUsed() bool {
	if x != nil {
		return x.Used
	}
	return false
}

func (x *OrmOutput) GetOrms() []*ORM {
	if x != nil {
		return x.Orms
	}
	return nil
}

type ORM struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//  name of orm
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	//  version of orm
	Version            string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	SupportedDbName    string `protobuf:"bytes,3,opt,name=supportedDbName,proto3" json:"supportedDbName,omitempty"`
	SupportedDbVersion string `protobuf:"bytes,4,opt,name=supportedDbVersion,proto3" json:"supportedDbVersion,omitempty"`
}

func (x *ORM) Reset() {
	*x = ORM{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_outputs_languageSpecific_orm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ORM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ORM) ProtoMessage() {}

func (x *ORM) ProtoReflect() protoreflect.Message {
	mi := &file_protos_outputs_languageSpecific_orm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ORM.ProtoReflect.Descriptor instead.
func (*ORM) Descriptor() ([]byte, []int) {
	return file_protos_outputs_languageSpecific_orm_proto_rawDescGZIP(), []int{1}
}

func (x *ORM) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ORM) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ORM) GetSupportedDbName() string {
	if x != nil {
		return x.SupportedDbName
	}
	return ""
}

func (x *ORM) GetSupportedDbVersion() string {
	if x != nil {
		return x.SupportedDbVersion
	}
	return ""
}

var File_protos_outputs_languageSpecific_orm_proto protoreflect.FileDescriptor

var file_protos_outputs_languageSpecific_orm_proto_rawDesc = []byte{
	0x0a, 0x29, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73,
	0x2f, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69,
	0x63, 0x2f, 0x6f, 0x72, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x39, 0x0a, 0x09, 0x4f,
	0x72, 0x6d, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x75, 0x73, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x04,
	0x6f, 0x72, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x4f, 0x52, 0x4d,
	0x52, 0x04, 0x6f, 0x72, 0x6d, 0x73, 0x22, 0x8d, 0x01, 0x0a, 0x03, 0x4f, 0x52, 0x4d, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x0f,
	0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x44, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64,
	0x44, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x12, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72,
	0x74, 0x65, 0x64, 0x44, 0x62, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x12, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x44, 0x62, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x23, 0x5a, 0x21, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x2f, 0x6c, 0x61, 0x6e, 0x67, 0x75,
	0x61, 0x67, 0x65, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_protos_outputs_languageSpecific_orm_proto_rawDescOnce sync.Once
	file_protos_outputs_languageSpecific_orm_proto_rawDescData = file_protos_outputs_languageSpecific_orm_proto_rawDesc
)

func file_protos_outputs_languageSpecific_orm_proto_rawDescGZIP() []byte {
	file_protos_outputs_languageSpecific_orm_proto_rawDescOnce.Do(func() {
		file_protos_outputs_languageSpecific_orm_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_outputs_languageSpecific_orm_proto_rawDescData)
	})
	return file_protos_outputs_languageSpecific_orm_proto_rawDescData
}

var file_protos_outputs_languageSpecific_orm_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_outputs_languageSpecific_orm_proto_goTypes = []interface{}{
	(*OrmOutput)(nil), // 0: OrmOutput
	(*ORM)(nil),       // 1: ORM
}
var file_protos_outputs_languageSpecific_orm_proto_depIdxs = []int32{
	1, // 0: OrmOutput.orms:type_name -> ORM
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_outputs_languageSpecific_orm_proto_init() }
func file_protos_outputs_languageSpecific_orm_proto_init() {
	if File_protos_outputs_languageSpecific_orm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_outputs_languageSpecific_orm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrmOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_outputs_languageSpecific_orm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ORM); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_outputs_languageSpecific_orm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_outputs_languageSpecific_orm_proto_goTypes,
		DependencyIndexes: file_protos_outputs_languageSpecific_orm_proto_depIdxs,
		MessageInfos:      file_protos_outputs_languageSpecific_orm_proto_msgTypes,
	}.Build()
	File_protos_outputs_languageSpecific_orm_proto = out.File
	file_protos_outputs_languageSpecific_orm_proto_rawDesc = nil
	file_protos_outputs_languageSpecific_orm_proto_goTypes = nil
	file_protos_outputs_languageSpecific_orm_proto_depIdxs = nil
}
