// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        (unknown)
// source: code-analyser/protos/output/languageSpecific/staticAssets.proto

package languageSpecific

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StaticAssetsOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// check assets
	Used bool `protobuf:"varint,1,opt,name=used,proto3" json:"used,omitempty"`
	// list of all assets
	Assets []*StaticAsset `protobuf:"bytes,2,rep,name=assets,proto3" json:"assets,omitempty"`
}

func (x *StaticAssetsOutput) Reset() {
	*x = StaticAssetsOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_code_analyser_protos_output_languageSpecific_staticAssets_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaticAssetsOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticAssetsOutput) ProtoMessage() {}

func (x *StaticAssetsOutput) ProtoReflect() protoreflect.Message {
	mi := &file_code_analyser_protos_output_languageSpecific_staticAssets_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaticAssetsOutput.ProtoReflect.Descriptor instead.
func (*StaticAssetsOutput) Descriptor() ([]byte, []int) {
	return file_code_analyser_protos_output_languageSpecific_staticAssets_proto_rawDescGZIP(), []int{0}
}

func (x *StaticAssetsOutput) GetUsed() bool {
	if x != nil {
		return x.Used
	}
	return false
}

func (x *StaticAssetsOutput) GetAssets() []*StaticAsset {
	if x != nil {
		return x.Assets
	}
	return nil
}

type StaticAsset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//  name of Asset
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	//  path of Asset
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	//
	Hashed bool `protobuf:"varint,3,opt,name=hashed,proto3" json:"hashed,omitempty"`
	Public bool `protobuf:"varint,4,opt,name=public,proto3" json:"public,omitempty"`
}

func (x *StaticAsset) Reset() {
	*x = StaticAsset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_code_analyser_protos_output_languageSpecific_staticAssets_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StaticAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticAsset) ProtoMessage() {}

func (x *StaticAsset) ProtoReflect() protoreflect.Message {
	mi := &file_code_analyser_protos_output_languageSpecific_staticAssets_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaticAsset.ProtoReflect.Descriptor instead.
func (*StaticAsset) Descriptor() ([]byte, []int) {
	return file_code_analyser_protos_output_languageSpecific_staticAssets_proto_rawDescGZIP(), []int{1}
}

func (x *StaticAsset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StaticAsset) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StaticAsset) GetHashed() bool {
	if x != nil {
		return x.Hashed
	}
	return false
}

func (x *StaticAsset) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

var File_code_analyser_protos_output_languageSpecific_staticAssets_proto protoreflect.FileDescriptor

var file_code_analyser_protos_output_languageSpecific_staticAssets_proto_rawDesc = []byte{
	0x0a, 0x3f, 0x63, 0x6f, 0x64, 0x65, 0x2d, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x65, 0x72, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x2f, 0x6c, 0x61,
	0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x2f, 0x73,
	0x74, 0x61, 0x74, 0x69, 0x63, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x4e, 0x0a, 0x12, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x41, 0x73, 0x73, 0x65, 0x74,
	0x73, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x75, 0x73, 0x65, 0x64, 0x12, 0x24, 0x0a, 0x06, 0x61,
	0x73, 0x73, 0x65, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x69, 0x63, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x06, 0x61, 0x73, 0x73, 0x65, 0x74,
	0x73, 0x22, 0x65, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x69, 0x63, 0x41, 0x73, 0x73, 0x65, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x61, 0x73, 0x68,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x68, 0x61, 0x73, 0x68, 0x65, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x42, 0x31, 0x5a, 0x2f, 0x63, 0x6f, 0x64, 0x65,
	0x2d, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2f, 0x70, 0x62, 0x2f, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x2f, 0x6c, 0x61, 0x6e, 0x67, 0x75,
	0x61, 0x67, 0x65, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_code_analyser_protos_output_languageSpecific_staticAssets_proto_rawDescOnce sync.Once
	file_code_analyser_protos_output_languageSpecific_staticAssets_proto_rawDescData = file_code_analyser_protos_output_languageSpecific_staticAssets_proto_rawDesc
)

func file_code_analyser_protos_output_languageSpecific_staticAssets_proto_rawDescGZIP() []byte {
	file_code_analyser_protos_output_languageSpecific_staticAssets_proto_rawDescOnce.Do(func() {
		file_code_analyser_protos_output_languageSpecific_staticAssets_proto_rawDescData = protoimpl.X.CompressGZIP(file_code_analyser_protos_output_languageSpecific_staticAssets_proto_rawDescData)
	})
	return file_code_analyser_protos_output_languageSpecific_staticAssets_proto_rawDescData
}

var file_code_analyser_protos_output_languageSpecific_staticAssets_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_code_analyser_protos_output_languageSpecific_staticAssets_proto_goTypes = []interface{}{
	(*StaticAssetsOutput)(nil), // 0: StaticAssetsOutput
	(*StaticAsset)(nil),        // 1: StaticAsset
}
var file_code_analyser_protos_output_languageSpecific_staticAssets_proto_depIdxs = []int32{
	1, // 0: StaticAssetsOutput.assets:type_name -> StaticAsset
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_code_analyser_protos_output_languageSpecific_staticAssets_proto_init() }
func file_code_analyser_protos_output_languageSpecific_staticAssets_proto_init() {
	if File_code_analyser_protos_output_languageSpecific_staticAssets_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_code_analyser_protos_output_languageSpecific_staticAssets_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaticAssetsOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_code_analyser_protos_output_languageSpecific_staticAssets_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StaticAsset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_code_analyser_protos_output_languageSpecific_staticAssets_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_code_analyser_protos_output_languageSpecific_staticAssets_proto_goTypes,
		DependencyIndexes: file_code_analyser_protos_output_languageSpecific_staticAssets_proto_depIdxs,
		MessageInfos:      file_code_analyser_protos_output_languageSpecific_staticAssets_proto_msgTypes,
	}.Build()
	File_code_analyser_protos_output_languageSpecific_staticAssets_proto = out.File
	file_code_analyser_protos_output_languageSpecific_staticAssets_proto_rawDesc = nil
	file_code_analyser_protos_output_languageSpecific_staticAssets_proto_goTypes = nil
	file_code_analyser_protos_output_languageSpecific_staticAssets_proto_depIdxs = nil
}
