# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos.plugin import common_pb2 as protos_dot_plugin_dot_common__pb2
from protos.plugin import env_pb2 as protos_dot_plugin_dot_env__pb2


class EnvServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Detect = channel.unary_unary(
                '/proto.EnvService/Detect',
                request_serializer=protos_dot_plugin_dot_common__pb2.ServiceInput.SerializeToString,
                response_deserializer=protos_dot_plugin_dot_env__pb2.ServiceOutputEnv.FromString,
                )


class EnvServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Detect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnvServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Detect': grpc.unary_unary_rpc_method_handler(
                    servicer.Detect,
                    request_deserializer=protos_dot_plugin_dot_common__pb2.ServiceInput.FromString,
                    response_serializer=protos_dot_plugin_dot_env__pb2.ServiceOutputEnv.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.EnvService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EnvService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Detect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.EnvService/Detect',
            protos_dot_plugin_dot_common__pb2.ServiceInput.SerializeToString,
            protos_dot_plugin_dot_env__pb2.ServiceOutputEnv.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
