name: CI

on:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Building docker
        run: docker-compose build
      - name: Start Docker Container
        run: docker-compose run --rm code-analyser bash
      - name: Installing Node Modules
        run: bash installNodeModulesPlugin.sh
      - name: Compile plugin binary
        run: bash compileGoPluginBinaries.sh
      - name: Test Case Run
        run: make test
